### ISSUE TITLE
11 JDK compatibility

### ISSUE THREAD

**Issue by ant-druha** [ant-druha/AppleScript-IDEA#4]
When opening file: 

```
java.lang.NoClassDefFoundError: org/omg/CORBA/StringHolder
	at com.intellij.plugin.applescript.lang.parser.AppleScriptGeneratedParserUtil.parseDictionaryConstant(AppleScriptGeneratedParserUtil.java:1168)
	at com.intellij.plugin.applescript.lang.parser.AppleScriptParser.dictionaryConstant(AppleScriptParser.java:2005)
	at com.intellij.plugin.applescript.lang.parser.AppleScriptParser.literalExpression(AppleScriptParser.java:4587)
	at com.intellij.plugin.applescript.lang.parser.AppleScriptParser.primaryExpression(AppleScriptParser.java:5305)
	at com.intellij.plugin.applescript.lang.parser.AppleScriptParser.valueExpression(AppleScriptParser.java:7904)
	at com.intellij.plugin.applescript.lang.parser.AppleScriptParser.prefixExpression(AppleScriptParser.java:5259)
	at com.intellij.plugin.applescript.lang.parser.AppleScriptParser.objectReferenceWrapper(AppleScriptParser.java:5035)
	at com.intellij.plugin.applescript.lang.parser.AppleScriptParser.powerExpressionWrapper(AppleScriptParser.java:5234)
	at com.intellij.plugin.applescript.lang.parser.AppleScriptParser.multiplicativeExpressionWrapper(AppleScriptParser.java:4807)
	at com.intellij.plugin.applescript.lang.parser.AppleScriptParser.additiveExpressionWrapper(AppleScriptParser.java:529)
	at com.intellij.plugin.applescript.lang.parser.AppleScriptParser.concatenationExpressionWrapper(AppleScriptParser.java:1423)
	at com.intellij.plugin.applescript.lang.parser.AppleScriptParser.coercionExpressionWrapper(AppleScriptParser.java:1235)
	at com.intellij.plugin.applescript.lang.parser.AppleScriptParser.compareExpressionWrapper(AppleScriptParser.java:1368)
	at com.intellij.plugin.applescript.lang.parser.AppleScriptParser.negationExpressionWrapper(AppleScriptParser.java:4910)
	at com.intellij.plugin.applescript.lang.parser.AppleScriptParser.logicalAndExpressionWrapper(AppleScriptParser.java:4642)
	at com.intellij.plugin.applescript.lang.parser.AppleScriptParser.logicalOrExpressionWrapper(AppleScriptParser.java:4692)
	at com.intellij.plugin.applescript.lang.parser.AppleScriptParser.expression(AppleScriptParser.java:2373)
	at com.intellij.plugin.applescript.lang.parser.AppleScriptParser.setCommandAppleScriptReturningSyntax(AppleScriptParser.java:6683)
	at com.intellij.plugin.applescript.lang.parser.AppleScriptParser.setCommandAppleScript(AppleScriptParser.java:6672)
	at com.intellij.plugin.applescript.lang.parser.AppleScriptParser.assignmentStatement(AppleScriptParser.java:951)
	at com.intellij.plugin.applescript.lang.parser.AppleScriptGeneratedParserUtil.parseAssignmentStatementInner(AppleScriptGeneratedParserUtil.java:336)
	at com.intellij.plugin.applescript.lang.parser.AppleScriptParser.parseAssignmentStatement(AppleScriptParser.java:5170)
	at com.intellij.plugin.applescript.lang.parser.AppleScriptParser.statement(AppleScriptParser.java:6864)
	at com.intellij.plugin.applescript.lang.parser.AppleScriptParser.topBlockBodyPart(AppleScriptParser.java:7248)
	at com.intellij.plugin.applescript.lang.parser.AppleScriptParser.compilation_unit_(AppleScriptParser.java:1392)
	at com.intellij.plugin.applescript.lang.parser.AppleScriptParser.appleScriptFile(AppleScriptParser.java:577)
	at com.intellij.plugin.applescript.lang.parser.AppleScriptParser.parse_root_(AppleScriptParser.java:402)
	at com.intellij.plugin.applescript.lang.parser.AppleScriptParser.parseLight(AppleScriptParser.java:396)
	at com.intellij.plugin.applescript.lang.parser.AppleScriptParser.parse(AppleScriptParser.java:18)
	at com.intellij.psi.tree.ILazyParseableElementType.doParseContents(ILazyParseableElementType.java:75)
	at com.intellij.psi.tree.IFileElementType.parseContents(IFileElementType.java:53)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.lambda$ensureParsed$0(LazyParseableElement.java:206)
	at com.intellij.psi.impl.DebugUtil.performPsiModification(DebugUtil.java:553)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.ensureParsed(LazyParseableElement.java:205)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:254)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:42)
	at com.intellij.psi.impl.source.tree.SharedImplUtil.getFirstChild(SharedImplUtil.java:51)
	at com.intellij.psi.impl.source.PsiFileImpl.getFirstChild(PsiFileImpl.java:725)
	at com.intellij.codeInsight.daemon.impl.Divider.divideInsideAndOutsideInOneRoot(Divider.java:121)
	at com.intellij.codeInsight.daemon.impl.Divider.divideInsideAndOutsideInOneRoot(Divider.java:71)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.doCollectInformation(LineMarkersPass.java:91)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:69)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:430)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1166)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:423)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:586)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:86)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:422)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:398)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:164)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:218)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:396)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:174)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
```

**Comment by ant-druha** [comment]
Fixed in 119
